##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build frontend docker images triggered by :
#  - push on main branch for latest tags 
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Supplychain Front-end Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'examples/supplychain-app/supplychain-frontend/**'
      - '.github/workflows/img_supplychain_frontend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to main branch, create docker tags latest
  frontend-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ env.IMAGE_PATH }}
             
    - name: Build and push supplychain front-end latest
      id: supplychain_frontend_latest
      uses: docker/build-push-action@v4
      with:
        context: examples/supplychain-app/supplychain-frontend
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-frontend:latest
