##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build express app docker image triggered by :
#  - push on main branch for latest tags
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Supplychain App Besu Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/img_supplychain_besu.yml'
      - 'examples/supplychain-app/besu/express_nodeJS/**'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to main branch, create docker tags latest
  besu-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ env.IMAGE_PATH }}
    
    - name: Check node version
      run: node -v

    - name: Build and push supplychain app latest
      id: besu_supplychain_latest
      uses: docker/build-push-action@v4
      with:
        context: ./examples/supplychain-app/besu/express_nodeJS
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-besu:express-app-latest
